import { IGame } from '../types'

export default [
  {
    id: 1,
    src: 'games/tower_game',
    name: '1',
    paused: false,
    liked: false,
  },
  {
    id: 2,
    src: 'games/0hh1_new',
    name: '2',
    paused: false,
    liked: false,
  },
  {
    id: 3,
    src: 'games/PixelOrbSword',
    name: '3',
    paused: false,
    liked: false,
  },
  {
    id: 4,
    src: 'games/hextris',
    name: '4',
    paused: false,
    liked: false,
  },
  {
    id: 5,
    src: 'games/regretris',
    name: '5',
    paused: false,
    liked: false,
  },
  {
    id: 6,
    src: 'games/turo3',
    name: '6',
    paused: false,
    liked: false,
  },
  {
    id: 7,
    src: 'games/test4',
    name: '7',
    paused: false,
    liked: false,
  },
  {
    id: 8,
    src: 'games/2048',
    name: '8',
    paused: false,
    liked: false,
  },
  {
    id: 9,
    src: 'games/PixelOrbMilk',
    name: '9',
    paused: false,
    liked: false,
  },
  // {
  //   id: 10,
  //   src: 'games/test4',
  //   name: '10',
  //   paused: false,
  //   liked: false,
  // },
  // {
  //   id: 11,
  //   src: 'games/test1',
  //   name: '11',
  //   paused: false,
  //   liked: false,
  // },
  // {
  //   id: 12,
  //   src: 'games/turo3',
  //   name: '12',
  //   paused: false,
  //   liked: false,
  // },
] as IGame[]